[package]
name = "engine"
version = "0.1.0"
authors = ["Timothée Haudebourg <timothee.haudebourg@hemisemi.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "*"
parking_lot = "*"

vulkano-win = "*"
winit = "*"
rand = "*"
bottle = { path = "./../../../design/bottle" }
async-std = { version = "*", features = ["attributes"] }
crossbeam-channel = "*"
